framework:
    messenger:
        # send failed messages to this transport for later handling.
        failure_transport: failed

        transports:
            async: 
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                retry_strategy:
                    max_retries: 0
            failed: '%env(MESSENGER_TRANSPORT_DSN_FAILURE)%'
            # sync: 'sync://'

        routing:
            # Route your messages to the transports
            App\Queue\Message\UserCreatedMessage: async
