image: gitlab/dind

stages:
 - test
 - build
 - deploy

test:
 type: test
 only:
    - master
    - develop
 image: php:7.4-fpm
 before_script:
   - apt-get update && apt-get install -y zip libzip-dev unzip git curl libfreetype6-dev libjpeg62-turbo-dev libxslt-dev libpng-dev && docker-php-ext-install -j$(nproc) gd xsl intl zip
   - apt install docker.io -y && service docker start
   - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
   - composer require symfony/messenger
   - composer install
 script:
   - php -d memory_limit=512M vendor/bin/phpstan analyse --ansi -c phpstan.neon -l 5 src
   - cp .env.test.dist .env.test
   - docker run -d -p 1025:1025 -p 8025:8025 mailhog/mailhog
   - php bin/phpunit

coverage:
  type: test
  only:
    - master
    - develop
  image: ciricihq/gitlab-sonar-scanner
  variables:
    SONAR_URL: http://161.35.6.31:9000
  script:
    - gitlab-sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=atoute-api -Dsonar.sources=.

build:
 type: build
 only:
   - master
 before_script:
   # Setup SSH deploy keys
   - echo "test issue"
   - 'which ssh-agent || ( apt-get install -qq openssh-client )'
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$PRIVATE_SSH_KEY")
   - mkdir -p ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   # Connection to Docker Hub
   - docker info
   - docker login registry.gitlab.com -u lucasconsejo -p TdQLTdyVMnL_D-NzqVRW
 script:
   - docker build -f Dockerfile-prod -t registry.gitlab.com/quentg/atoute-back/api .
   - docker push registry.gitlab.com/quentg/atoute-back/api

deploy:
 type: deploy
 only:
   - master
 before_script:
   # Setup SSH deploy keys
   - echo "test issue"
   - 'which ssh-agent || ( apt-get install -qq openssh-client )'
   - eval $(ssh-agent -s)
   - ssh-add <(echo "$PRIVATE_SSH_KEY")
   - mkdir -p ~/.ssh
   - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
   # Connection to Docker Hub
   - docker info
   - docker login registry.gitlab.com -u lucasconsejo -p TdQLTdyVMnL_D-NzqVRW
 script:
   - ssh root@142.93.52.107 "cd /atoute && ./deploy.sh && exit"
