image: gitlab/dind

stages:
  - test
  - build
  - deploy

before_script:
  # Setup SSH deploy keys
  - 'which ssh-agent || ( apt-get install -qq openssh-client )'
  - eval $(ssh-agent -s)
  - ssh-add <(echo "$PRIVATE_SSH_KEY")
  - mkdir -p ~/.ssh
  - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
  # Connection to Docker Hub
  - docker info
  - docker login registry.gitlab.com -u lucasconsejo -p TdQLTdyVMnL_D-NzqVRW

test:
  type: test
  image: php:7.4-fpm
  before_script:
    - apt-get update && apt-get install -y zip libzip-dev unzip git curl libfreetype6-dev libjpeg62-turbo-dev libxslt-dev libpng-dev && docker-php-ext-install -j$(nproc) gd xsl intl zip
    - apt install docker.io -y && service docker start
    - curl --silent --show-error https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    - composer install
  script:
    - php -d memory_limit=512M vendor/bin/phpstan analyse --ansi -c phpstan.neon -l 5 src
    - cp .env.test.dist .env.test
#    - docker run -d -p 1026:1025 -p 8026:8025 --name mail_unit mailhog/mailhog
    - php bin/phpunit
    - docker stop mail_unit && docker rm mail_unit -f

build:
  type: build
  script:
    - docker build -f Dockerfile-prod -t registry.gitlab.com/quentg/atoute-back/api .
    - docker push registry.gitlab.com/quentg/atoute-back/api

deploy:
  type: deploy
  script:
    - ssh root@206.189.201.153 "/atoute/back/deploy.sh && exit"
