version: '3'

services:
  php:
    build: . # Build avec le Dockerfile
    image: php:7.4-apache
    depends_on:
      - mysql
    # Changement du répertoire courant
    working_dir: /var/www/html/back
    volumes:
      - .:/var/www/html/back
    extra_hosts:
      - "back-local.atoute.com:127.0.0.1"
    # Définition du port sur lequel écouté, on le lie au port 8080 local "portchoisi:portapache"
    ports:
      - "8080:80"

  mysql:
    image: mysql:5.7
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--lower_case_table_names=1"
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass0
      # Variables d'environnement pour se connecter à la base de données
      - MYSQL_DATABASE=atoute
      - MYSQL_USER=atoute
      - MYSQL_PASSWORD=atoute
    ports:
      - "3306:3306"

  mail:
    image: mailhog/mailhog:latest
    ports:
      - "1025:1025"
      - "8025:8025"