#!/bin/sh

# Fetch the GIT diff and format it as command input:
DIFF=$(git -c diff.mnemonicprefix=false --no-pager diff -r -p -m -M --full-index --no-color --staged | cat)

# Run GrumPHP
(printf "%s\n" "${DIFF}" | docker exec -i atoute_back_php_1 bash -c "php -d memory_limit=512M vendor/bin/grumphp git:pre-commit --ansi --skip-success-output")