parameters:
    uploadsRelativeDir: 'uploads/'
    uploadsAbsoluteDir: '%kernel.project_dir%/public/%uploadsRelativeDir%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind: # Retrieve these parameters throughout the project
            $uploadsAbsoluteDir: '%uploadsAbsoluteDir%'
            $uploadsRelativeDir: '%uploadsRelativeDir%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\EventListener\EntityListener:
        tags:
            - { name: doctrine.event_listener, event: prePersist }
            - { name: doctrine.event_listener, event: preUpdate }
            - { name: doctrine.event_listener, event: postPersist }
            - { name: doctrine.event_listener, event: postUpdate }

    App\EventListener\LogoutListener:
        tags:
            - name: 'kernel.event_listener'
              event: 'Symfony\Component\Security\Http\Event\LogoutEvent'
              dispatcher: security.event_dispatcher.api

    gesdinet.jwtrefreshtoken.refresh_token_manager:
        class: App\Doctrine\RefreshTokenManager
        public: true
        arguments: [ '@gesdinet.jwtrefreshtoken.object_manager', '%gesdinet.jwtrefreshtoken.refresh_token.class%' ]

    App\Service\MailerService:
        arguments:
            $from: '%env(MAILER_FROM)%'

    Elastica\Client:
        $config:
            host: 'elasticsearch' # or 127.0.0.1